---
- name: Setup PXE Server on Controller
  hosts: controller
  become: yes
  vars_files:
    - vars/pxe_vars.yml

  tasks:
    - name: Install dnsmasq and nginx
      apt:
        name:
          - dnsmasq
          - nginx
        state: present
        update_cache: yes

    - name: Create TFTP and HTTP directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /srv/tftp
        - /srv/tftp/pxelinux.cfg
        - /srv/http/ubuntu

    - name: Configure dnsmasq for PXE boot
      template:
        src: templates/dnsmasq-pxe.conf.j2
        dest: /etc/dnsmasq.d/pxe-server.conf

    - name: Configure PXE boot menu
      template:
        src: templates/pxelinux.cfg-default.j2
        dest: /srv/tftp/pxelinux.cfg/default
        mode: '0644'

    - name: Download netboot files
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop: "{{ netboot_files }}"

    - name: Extract netboot files
      unarchive:
        src: /tmp/netboot.tar.gz
        dest: /srv/tftp
        remote_src: yes

    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
        enabled: yes

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: Copy cloud-init files to PXE server
      copy:
        src: cloud-init/
        dest: /srv/http/cloud-init/
        mode: '0755'

    - name: Copy PXE boot menu
      copy:
        src: pxe-menu/pxelinux.cfg/
        dest: /srv/tftp/pxelinux.cfg/
        mode: '0755'